version: '3'

services:
  zxing-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - GIN_MODE=release
    restart: unless-stopped 