name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.19.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install -y libzxing-dev
        sudo apt-get install -y python3

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        vcpkg install zxing-cpp:x64-windows
        python -m pip install --upgrade pip

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake
        brew install zxing-cpp
        brew install python3

    - name: Build
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          .\build.bat
        else
          chmod +x build.sh
          ./build.sh
        fi

    - name: Run tests
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          go test -v ./...
        else
          go test -v ./...
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          build/
          dist/
        if-no-files-found: error

  package-deb:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-ubuntu-latest
        path: build/
    
    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper dh-make
    
    - name: Create DEB package
      run: |
        VERSION=$(echo ${GITHUB_REF#refs/tags/v})
        ./scripts/build_deb.sh $VERSION
    
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: dist/*.deb
        if-no-files-found: error

  package-rpm:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-ubuntu-latest
        path: build/
    
    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm rpm-build
    
    - name: Create RPM package
      run: |
        VERSION=$(echo ${GITHUB_REF#refs/tags/v})
        ./scripts/build_rpm.sh $VERSION
    
    - name: Upload RPM package
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: dist/*.rpm
        if-no-files-found: error

  release:
    needs: [package-deb, package-rpm]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download packages
      uses: actions/download-artifact@v4
      with:
        path: dist/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.deb
          dist/*.rpm
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 